###############################################################################
# RELEASE
###############################################################################

name: Publish


###############################################################################
# ON
###############################################################################

on:
  push:
    tags:
      - '*'


###############################################################################
# JOBS
###############################################################################

jobs:

  build:

    name: Release in GitHub
    runs-on: "ubuntu-latest"
    permissions:
      contents: write

    ###########################################################################
    # STEPS
    ###########################################################################

    steps:

      #########################################################################
      # INIT
      #########################################################################
      - name: checks-out repository
        uses: actions/checkout@v3

      # PNPM
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install

      #########################################################################
      # IF IS IN MAIN BRANCH
      #########################################################################

      # - name: Exit if not on MAIN branch
      #   if: endsWith(github.ref, 'main') == false
      #   run: exit -1

      #########################################################################
      # BUILD PKG
      #########################################################################

      - name: Install pkg dependencies
        run: |
          pnpm i
          pnpm check
          pnpm build
        env:
          GITHUB_TOKEN: ${{ github.token }}

      #########################################################################
      # GET PKG INFO
      #########################################################################

      - name: Get package info
        id: package
        uses: codex-team/action-nodejs-package-info@v1.1

      #########################################################################
      # GITHUB RELEASE
      #########################################################################

      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip"
          bodyFile: ".utils/releaseFile.md"


############################################################################### 